name: Daily Job Search

on:
  workflow_dispatch:    # permite ejecución manual
  schedule:
    - cron: '0 0 * * *'  # cada día a medianoche UTC

jobs:
  run-job-search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug: listar todos los archivos en el workspace
        run: |
          echo "=== Listado de archivos en el workspace ==="
          ls -R .

      - name: Debug: mostrar las primeras líneas de applications.py
        run: sed -n '1,5p' applications.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client gspread-dataframe \
                      requests beautifulsoup4 pandas

      - name: Create credentials file
        run: echo "$GDRIVE_CREDENTIALS" > credentials.json

      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json
        run: python applications.py

