name: Daily Job Search

on:
  workflow_dispatch:    # manual trigger
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC

jobs:
  run-job-search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client gspread-dataframe \
                      requests beautifulsoup4 pandas

      - name: Create credentials file
        # Replace SECRET_NAME with the name of your GitHub Actions secret
        run: echo "${{ secrets.SECRET_NAME }}" > credentials.json

      - name: Run script
        env:
          # Point to the JSON just created
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json
        run: python applications.py
