name: Daily Job Search

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-job-search:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install \
            gspread oauth2client gspread-dataframe \
            requests beautifulsoup4 pandas

      - name: Create credentials file
        run: |
          # This preserves the exact JSON (including newlines)
          cat <<EOF > credentials.json
          ${{ GDRIVE_CREDENTIALS }}
          EOF

      - name: Run script
        env:
          # Let the Google client library pick it up
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json
        run: python applications.py
